spring:
  application:
    name: VKBot

vk:
  api:
    key: ${VK_API_KEY}
  callback:
    api:
      secret: ${VK_CALLBACK_API_SECRET}
      confirm: ${VK_CALLBACK_API_CONFIRM}
server:
  port: 5173
logging:
  level:
    ru.alex9043.vkbot.service.VKBotService: DEBUG