spring:
  application:
    name: VKBot

server:
  port: ${SERVER_PORT}

#logging:
#  level:
#    ru.alex9043.vkbot: ${LOGGING_LEVEL}

vk:
  api:
    key: ${VK_API_KEY}
    url: ${VK_API_URL}
  callback:
    api:
      secret: ${VK_CALLBACK_API_SECRET}
      confirm: ${VK_CALLBACK_API_CONFIRM}
      version: ${VK_CALLBACK_API_VERSION}