spring:
  application:
    name: VKBot

server:
  port: 5173

logging:
  level:
    ru.alex9043.vkbot: INFO

vk:
  api:
    key: ${VK_API_KEY}
  callback:
    api:
      secret: ${VK_CALLBACK_API_SECRET}
      confirm: ${VK_CALLBACK_API_CONFIRM}
      version: 5.199


